#!/bin/bash
# Generate GitInfo.swift with current branch and commit hash.
# Called by xcodegen postGenCommand and can be run manually.
set -euo pipefail

cd "$(dirname "$0")/.."

BRANCH=$(git -C .. rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
COMMIT=$(git -C .. rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > WingDex/App/GitInfo.swift << SWIFT
// Auto-generated by scripts/gen-git-info.sh - do not edit
enum GitInfo {
    static let branch = "$BRANCH"
    static let commit = "$COMMIT"
}
SWIFT
