interface Env {
  DB: D1Database
  AI: Ai
  BETTER_AUTH_URL: string
  BETTER_AUTH_SECRET: string
  GITHUB_CLIENT_ID: string
  GITHUB_CLIENT_SECRET: string
  APPLE_CLIENT_ID: string
  APPLE_CLIENT_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  LLM_PROVIDER: string
  OPENAI_API_KEY: string
  OPENAI_MODEL: string
  AZURE_OPENAI_ENDPOINT: string
  AZURE_OPENAI_API_KEY: string
  AZURE_OPENAI_DEPLOYMENT: string
  AZURE_OPENAI_API_VERSION: string
  GITHUB_MODELS_TOKEN: string
  GITHUB_MODELS_ENDPOINT: string
  GITHUB_MODELS_MODEL: string
  CF_ACCOUNT_ID: string
  AI_GATEWAY_ID: string
}
